---
title: "HJA.Rmd"
output: pdf_document
---
### Initial Setup
```{r}
rm(list=ls())
setwd("~/GitHub/HJA-streams/")
source("./analysis/MothurTools.R")

require("vegan")
require("png")

se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
```


### Import Shared and Design Files
```{r}
# Define Inputs
# Design = general design file for experiment
# shared = OTU table from mothur with sequence similarity clustering
# Taxonomy = Taxonomic information for each OTU
design <- "./data/design.txt"
shared <- "./data/hja_streams.final.shared"
taxon  <- "./data/hja_streams.final.0.03.taxonomy"
env    <- "./data/hja_env.csv"

# Import Design
design <- read.delim(design, header=T, row.names=1)

# Import Shared Files
OTUs <- read.otu(shared = shared, cutoff = "0.03")         # 97% Similarity

# Import Taxonomy
OTU.tax <- read.tax(taxonomy = taxon, format = "rdp")

# Import Env
env <- read.csv(env, header=T)
```


### Data Transormations
```{r}
# Remove OTUs with less than two occurances across all sites
OTUs <- OTUs[, which(colSums(OTUs) >= 2)]

# Sequencing an Good's Coverage
# Sequencing Coverage
coverage <- rowSums(OTUs)

# Good's Coverage
goods <- function(x = ""){
  1 - (sum(x == 1) / rowSums(x))
}
goods.c <- goods(OTUs)

# Remove Low Coverage Samples (This code removes two sites: Site 5DNA, Site 6cDNA)
lows <- which(coverage < 7000)
lows
OTUs <- OTUs[-which(coverage < 7000), ]
design <- design[-which(coverage < 7000), ]
env <- env[-which(coverage < 7000), ]

# Make Relative Abundence Matrices
OTUsREL <- OTUs
for(i in 1:dim(OTUs)[1]){
  OTUsREL[i,]<- OTUs[i,]/sum(OTUs[i,])
}

# Log Transform Relative Abundances
OTUsREL.log <- decostand(OTUs, method="log")

```

### Calculate Alpha Diversity
```{r}
# Observed Richness
S.obs <- rowSums((OTUs > 0) * 1)

# Simpson's Evenness
SimpE <- function(x = ""){
  x <- as.data.frame(x)
  D <- diversity(x, "inv")
  S <- sum((x > 0) * 1) 
  E <- (D)/S 
  return(E)
}
simpsE <- round(apply(OTUs, 1, SimpE), 3)

# Shannon's Diversity
H <- function(x = ""){
  x <- x[x>0]
  H = 0
  for (n_i in x){
    p = n_i / sum(x)
    H = H - p*log(p) 
  }
  return(H)
}

shan <- round(apply(OTUs, 1, H), 2)
shan2 <- diversity(OTUs, index = "shannon")

# Rarefaction
hja.S <- rowSums((OTUs > 0) * 1)
min.N <- min(rowSums(OTUs))
#S.rarefy <- rarefy(x = OTUs, sample = min.N, se = TRUE)
#rarecurve(x = OTUs, step = 20, col = "blue", cex = 0.6, las = 1)
#rared <- t(S.rarefy)

alpha.div <- cbind(design, S.obs, simpsE, shan)
```


## Alpha Diversity Across Gradient
```{r}
# Seperate data based on water and sediment samples
water <- alpha.div[alpha.div$habitat == "water",]
sed <- alpha.div[alpha.div$habitat == "sediment", ]

lc   <- alpha.div[alpha.div$watershed == "LC",]
ws01 <- alpha.div[alpha.div$watershed == "WS01",]

# Calculate Linear Model
model.rich <- lm(alpha.div$S.obs ~ alpha.div$habitat)
summary(model.rich)

model.div <- lm(alpha.div$shan ~ alpha.div$habitat)
summary(model.div)

model.even <- lm(alpha.div$simpsE ~ alpha.div$habitat)
summary(model.even)

# Calculate Confidance Intervals of Model
newdata.rich <- data.frame(alpha.div$habitat)
conf95.rich <- predict(model.rich, newdata.rich, interval="confidence")
```


### PCoA

# HJA PCoA
```{r}
# All HJA Catchment
hja.db <- vegdist(OTUsREL, method = "bray", upper = TRUE, diag = TRUE)
hja.pcoa <- cmdscale(hja.db, eig=TRUE, k=3)
var1 <- round(hja.pcoa$eig[1] / sum(hja.pcoa$eig),3) * 100
var2 <- round(hja.pcoa$eig[2] / sum(hja.pcoa$eig),3) * 100
var3 <- round(hja.pcoa$eig[3] / sum(hja.pcoa$eig),3) * 100

# Sediments Only
sediment <- OTUsREL.log[which(design$habitat == "sediment"),]
sediment.db <- vegdist(sediment, method = "bray", diag = T)
sediment.pcoa <- cmdscale(sediment.db, eig=TRUE, k=3)
sed.design <- design[which(design$habitat == "sediment"),]
s.var1 <- round(sediment.pcoa$eig[1] / sum(sediment.pcoa$eig),3) * 100
s.var2 <- round(sediment.pcoa$eig[2] / sum(sediment.pcoa$eig),3) * 100
s.var3 <- round(sediment.pcoa$eig[3] / sum(sediment.pcoa$eig),3) * 100

# Water Only
water <- OTUsREL.log[which(design$habitat == "water"),]
water.db <- vegdist(water, method = "bray", diag = T)
water.pcoa <- cmdscale(water.db, eig=TRUE, k=3)
water.design <- design[which(design$habitat == "water"),]
w.var1 <- round(water.pcoa$eig[1] / sum(water.pcoa$eig),3) * 100
w.var2 <- round(water.pcoa$eig[2] / sum(water.pcoa$eig),3) * 100
w.var3 <- round(water.pcoa$eig[3] / sum(water.pcoa$eig),3) * 100

# Lookout Creek Watershed Only
lc <- OTUsREL[which(design$watershed == "LC"),]
lc.db <- vegdist(lc, method = "bray", diag = T)
lc.pcoa <- cmdscale(lc.db, eig=TRUE, k=3)
lc.design <- design[which(design$watershed == "LC"),]
lc.var1 <- round(lc.pcoa$eig[1] / sum(lc.pcoa$eig),3) * 100
lc.var2 <- round(lc.pcoa$eig[2] / sum(lc.pcoa$eig),3) * 100
lc.var3 <- round(lc.pcoa$eig[3] / sum(lc.pcoa$eig),3) * 100

# Watershed 01 Only
w1 <- OTUsREL[which(design$watershed == "WS01"),]
w1.db <- vegdist(w1, method = "bray", diag = T)
w1.pcoa <- cmdscale(w1.db, eig=TRUE, k=3)
w1.design <- design[which(design$watershed == "WS01"),]
w1.var1 <- round(w1.pcoa$eig[1] / sum(w1.pcoa$eig),3) * 100
w1.var2 <- round(w1.pcoa$eig[2] / sum(w1.pcoa$eig),3) * 100
w1.var3 <- round(w1.pcoa$eig[3] / sum(w1.pcoa$eig),3) * 100
```

# Plot HJA PCoA Figure
```{r}
png(filename = "./figures/Figure1.png",
    width = 1200, height = 1200, res = 96*2)

par(mar = c(5, 5, 3, 2) + 0.1)
plot(hja.pcoa$points[ ,1], hja.pcoa$points[ ,2], ylim = c(-0.5, 0.4),
     xlab = paste("PCoA 1 (", var1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", var2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F,
     main="H.J. Andrews Catchment")
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(hja.pcoa$points[which(design$habitat == "sediment"),1], 
       hja.pcoa$points[which(design$habitat == "sediment"),2],
       pch=19, cex=2, bg="wheat", col="wheat")
points(hja.pcoa$points[which(design$habitat == "water"),1], 
       hja.pcoa$points[which(design$habitat == "water"),2],
       pch=19, cex=2, bg="skyblue", col="skyblue")
text(hja.pcoa$points[ ,1], hja.pcoa$points[ ,2],
     cex = 0.5, labels = row.names(hja.pcoa$points))

require("BiodiversityR")
fish.pcoa <-


dev.off()
graphics.off()
```

# Plot other PCoA figures
```{r}
opar <- par()

png(filename = "./figures/Figure2.png",
    width = 2400, height = 1200, res = 96*2)
par(mfrow = c(1,2))

# Sediments PCoA
par(mar = c(5, 5, 3, 2) + 0.1)
plot(sediment.pcoa$points[ ,1], sediment.pcoa$points[ ,2], ylim = c(-0.4, 0.5),
     xlab = paste("PCoA 1 (", s.var1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", s.var2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F,
     main="Sediments")
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(sediment.pcoa$points[which(sed.design$watershed == "LC"),1], 
       sediment.pcoa$points[which(sed.design$watershed == "LC"),2],
       pch=19, cex=2, bg="orchid", col="orchid")
points(sediment.pcoa$points[which(sed.design$watershed == "WS01"),1], 
       sediment.pcoa$points[which(sed.design$watershed == "WS01"),2],
       pch=19, cex=2, bg="yellowgreen", col="yellowgreen")
text(sediment.pcoa$points[ ,1], sediment.pcoa$points[ ,2],
     cex=0.5, labels = row.names(sediment.pcoa$points))

# Water PCoA
par(xpd=True, mar = c(5, 5, 3, 2) + 0.1)
plot(water.pcoa$points[ ,1], water.pcoa$points[ ,2], ylim = c(-0.4, 0.35),
     xlab = paste("PCoA 1 (", w.var1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", w.var2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F,
     main="Water")
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(water.pcoa$points[which(water.design$watershed == "LC"),1], 
       water.pcoa$points[which(water.design$watershed == "LC"),2],
       pch=19, cex=2, bg="orchid", col="orchid")
points(water.pcoa$points[which(water.design$watershed == "WS01"),1], 
       water.pcoa$points[which(water.design$watershed == "WS01"),2],
       pch=19, cex=2, bg="yellowgreen", col="yellowgreen")
text(water.pcoa$points[ ,1], water.pcoa$points[ ,2],
     cex=0.5, labels = row.names(water.pcoa$points))

dev.off()
graphics.off()


png(filename = "./figures/Figure3.png",
    width = 2400, height = 1200, res = 96*2)
par(mfrow = c(1,2))

# Lookout Creek PCoA
par(mar = c(5, 5, 3, 2) + 0.1)
plot(lc.pcoa$points[ ,1], lc.pcoa$points[ ,2], ylim = c(-0.4, 0.35),
     xlab = paste("PCoA 1 (", lc.var1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", lc.var2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F,
     main="Lookout Creen Watershed")
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(lc.pcoa$points[which(lc.design$habitat == "water"),1], 
       lc.pcoa$points[which(lc.design$habitat == "water"),2],
       pch=19, cex=2, bg="skyblue", col="skyblue")
points(lc.pcoa$points[which(lc.design$habitat == "sediment"),1], 
       lc.pcoa$points[which(lc.design$habitat == "sediment"),2],
       pch=19, cex=2, bg="wheat", col="wheat")
text(lc.pcoa$points[ ,1], lc.pcoa$points[ ,2],
     cex=0.5, labels = row.names(lc.pcoa$points))

# WS01 PCoA
par(mar = c(5, 5, 3, 2) + 0.1)
plot(w1.pcoa$points[ ,1], w1.pcoa$points[ ,2], ylim = c(-0.4, 0.35),
     xlab = paste("PCoA 1 (", w1.var1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", w1.var2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F,
     main="Watershed 01")
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(w1.pcoa$points[which(w1.design$habitat == "water"),1], 
       w1.pcoa$points[which(w1.design$habitat == "water"),2],
       pch=19, cex=2, bg="skyblue", col="skyblue")
points(w1.pcoa$points[which(w1.design$habitat == "sediment"),1], 
       w1.pcoa$points[which(w1.design$habitat == "sediment"),2],
       pch=19, cex=2, bg="wheat", col="wheat")
text(w1.pcoa$points[ ,1], w1.pcoa$points[ ,2],
     cex=0.5, labels = row.names(w1.pcoa$points))

dev.off()
graphics.off()
```


```{r, eval=FALSE}
require("simba")

#png(filename="./figures/Figure4.png", width=1200, height=1200, res=96*2)
#par(mfrow=c(2,1))
# water Distance Decay
water.lat <- as.numeric(env$latitude[which(design$habitat == "water")])
water.lon <- as.numeric(env$longitude[which(design$habitat == "water")])

water.struc.dist <- 1 - vegdist(OTUs.REL.log[which(design$habitat == "water"),])
water.coord.dist <- dist(as.matrix(water.lat, water.lon))
water.env.dist <- 1 - vegdist(env[which(design$habitat == "water"), 10:16])

water.struc.dist.ls <- liste(water.struc.dist, entry = "struc")
water.env.dist.ls <- liste(water.env.dist, entry = "env")
water.coord.dist.ls <- liste(water.coord.dist, entry = "dist")

water.distances <- data.frame(water.coord.dist.ls, water.env.dist.ls[,3], water.struc.dist.ls[,3])
names(water.distances)[4:5] <- c("env", "struc")

plot(water.distances$dist, water.distances$struc, xlab="Geographic Distance", 
     ylab = "Bray-Curtis Similarity", main = "Water Distance-Decay")
water.lm <- abline(lm(water.distances$struc ~ water.distances$dist))


# sediment Distance Decay
sed.lat <- as.numeric(env$latitude[which(design$habitat == "sediment")])
sed.lon <- as.numeric(env$longitude[which(design$habitat == "sediment")])

sed.struc.dist <- 1 - vegdist(OTUsREL.log[which(design$habitat == "sediment"),])
sed.coord.dist <- dist(as.matrix(sed.lat, sed.lon))
sed.env.dist <- 1 - vegdist(env[which(design$habitat == "sediment"), 10:16])

sed.struc.dist.ls <- liste(sed.struc.dist, entry = "struc")
sed.env.dist.ls <- liste(sed.env.dist, entry = "env")
sed.coord.dist.ls <- liste(sed.coord.dist, entry = "dist")

sed.distances <- data.frame(sed.coord.dist.ls, sed.env.dist.ls[,3], sed.struc.dist.ls[,3])
names(sed.distances)[4:5] <- c("env", "struc")

plot(sed.distances$dist, sed.distances$struc, xlab="Geographic Distance", 
     ylab = "Bray-Curtis Similarity", main = "Sediment Distance-Decay")
sed.lm <- abline(lm(sed.distances$struc ~ sed.distances$dist))

dev.off()
graphics.off()

diffslope(sed.distances$dist, sed.distances$struc, water.distances$dist, water.distances$struc)

```


```{r}

hja.bray <- 1 - as.matrix(vegdist(OTUsREL.log, method = "bray"))
hja.bray.mean <- round(apply(hja.bray, 1, mean), 3)
hja.bray.se <- round(apply(hja.bray, 1, se), 3)
hja.sim <- cbind(design, hja.bray.mean, hja.bray.se)
model.hja <- lm(hja.sim$hja.bray.mean ~ hja.sim$elev * hja.sim$habitat)
summary(model.hja)
plot(hja.sim$hja.bray.mean ~ hja.sim$elev, main = "HJA Catchment",
     ylab = "Bray-Curtis Similarity", xlab = "Elevation")
abline(model.hja)

png(filename = "./figures/Figure4.png", 
    width = 1200, height = 1200, res = 96*2)
par(mfrow = c(2, 1), mar = c(5, 5, 2, 3) + 0.1)
water.bray <- 1 - as.matrix(vegdist(OTUsREL.log[which(design$habitat=="water"),], method = "bray"))
water.bray.mean <- round(apply(water.bray, 1, mean), 3)
water.bray.se <- round(apply(water.bray, 1, se), 3)
water.sim <- cbind(water.design, water.bray.mean, water.bray.se)
model.water <- lm(water.sim$water.bray.mean ~ water.sim$elev)
summary(model.water)
plot(water.sim$water.bray.mean ~ water.sim$elev, xlab="",
     ylab = "", main="Bray-Curtis Similarity")
mtext("Surface Water", side = 2, line = 3, cex = 1.5)
mtext("Bray-Curtis Similarity", side=3, line=3, cex=1.5)
abline(model.water)

sed.bray <- 1 - as.matrix(vegdist(OTUsREL.log[which(design$habitat=="sediment"),], method = "bray"))
sed.bray.mean <- round(apply(sed.bray, 1, mean), 3)
sed.bray.se <- round(apply(sed.bray, 1, se), 3)
sed.sim <- cbind(sed.design, sed.bray.mean, sed.bray.se)
model.sed <- lm(sed.sim$sed.bray.mean ~ sed.sim$elev)
summary(model.sed)
plot(sed.sim$sed.bray.mean ~ sed.sim$elev, xlab="",
     ylab = "")
abline(model.sed)
mtext("Sediments", side = 2, line = 3, cex = 1.5)
mtext("Distance (m)", side = 1, line = 3, cex = 1.5)

dev.off()
graphics.off()
```


```{r}
require('igraph')
adj.mat <- as.matrix(read.csv("./data/undirected-matrix.csv", header=T))
row.names(adj.mat) <- adj.mat[,1]
adj.mat <- adj.mat[,-1]
adj.mat <- (adj.mat == 1) * 1


stream.network <- graph_from_adjacency_matrix(adjmatrix = adj.mat)
plot.igraph(stream.network,... =  cex=0.5)
```

### CCA
```{r, eval=FALSE}
#env.mat <- as.matrix(env[which(env$habitat == "hja"),10:17])
env.mat <- as.matrix(env[,10:17])
hja.cca <- vegan::cca(OTUs ~ env.mat) 
#anova(hja.cca, by = "axis")
cca.fit <- envfit(hja.cca, env.mat, perm = 999)
cca.explainvar1 <- round(hja.cca$CCA$eig[1] /
                           sum(c(hja.cca$CCA$eig, hja.cca$CA$eig)), 3) * 100
cca.explainvar2 <- round(hja.cca$CCA$eig[2] /
                           sum(c(hja.cca$CCA$eig, hja.cca$CA$eig)), 3) * 100

par(mar = c(5, 5, 4, 4) + 0.1)
plot(scores(hja.cca, display = "wa"), xlim = c(-2, 2.5), ylim = c(-4, 2),
     xlab = paste("CCA 1 (", cca.explainvar1, "%)", sep = ""), 
     ylab = paste("CCA 2 (", cca.explainvar2, "%)", sep = ""), 
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)
axis(side=1, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
axis(side=2, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
abline(h=0, v=0, lty=3)
box(lwd=2)
points(scores(hja.cca, display = "wa"),
       pch=19, cex=3, bg="gray", col="gray")
text(scores(hja.cca, display = "wa"),
     labels = row.names(scores(hja.cca, display = "wa")))
```