require(vegan)
require("EcoGenetics")
OTUsREL <- decostand(otu.in, method = "total")
OTUsREL.detrend <- eco.detrend(Z = OTUsREL, XY = as.data.frame(xy), degree = 1)
save(OTUsREL.detrend, file = "./data/detrend-sbys.txt")
OTUs.det <- ecoslot.RES(OTUsREL.detrend)

min(OTUs.det + abs(min(OTUs.det)))
det.bray <- vegdist((OTUs.det + abs(min(OTUs.det))), method = "bray")
det.bray.pcoa <- cmdscale(det.bray)
adonis(det.bray ~ design$habitat)
plot(det.bray.pcoa)
ordiellipse(det.bray.pcoa, design$habitat, conf = 0.95)
